# Generated by Django 3.0.7 on 2020-07-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0003_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='camp_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sent_to',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
